### PR TITLE
Hacky workarounds

### PR DESCRIPTION
**Pull request by DaMatrix**
I'm unable to start and connect to the server without this, figured you could have a look

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
Calling @MarfGamer since this error doesn't happen for me.

Stacktrace:

**Comment by DaMatrix** [comment]
It's fixed by this:
https://github.com/PocketDreams/SequinLand-Glowstone/pull/2/files#diff-4a53b3381941673e3c193b239a370f17R598

**Comment by whirvis** [comment]
There was a NullPointerException using a method that returned a native type, so there is no way that getMaximumTransferUnit() is returning null. Are you sure the server isn't null? I just now rewrote the getMaximumTransferUnit() to return -1 for any throwable. When I fix JRakNet issue #30 and #31 I will push with this fix.

**Comment by whirvis** [comment]
Also I noticed in your constructor for the server you set the server MCPEIdentifer online players to the current server size. While this code will run it will most likely be inaccurate, override the handlePing() method to make sure the data sent when a client pings the server for it's Identifier is up-to-date.

**Comment by MrPowerGamerBR** [comment]
@MarfGamer maybe I also should do that to my Nukkit fork too, thanks for the info!

(This is only a WIP project, very WIP, so much WIP, wow... this project aims to add Minecraft Pocket/Windows 10 Edition to Glowstone, it isn't working yet... but hey, you can login and view the world chunks! So that's something)

**Comment by whirvis** [comment]
Hey, if you can I need you to join the test server with me so we can mess around until one of us stops receiving packets again and see if any of the addresses are blocked.

**Comment by MrPowerGamerBR** [comment]
@MarfGamer okay

**Comment by whirvis** [comment]
It's updated to print out all blocked addresses, right?

**Comment by MrPowerGamerBR** [comment]
@MarfGamer yep

**Comment by whirvis** [comment]
I just got disconnected now

**Comment by DaMatrix** [comment]
Alright, merge conflicts are resolved.

**Pull request merged**
