### PR TITLE
Allow users to change PE port

### PR DESCRIPTION
**Pull request by DaMatrix**

### CODE REVIEW

**Comment by MrPowerGamerBR** [comment]
I will probably create a separate config for Pocket configurations. (called sequinland.yml)

**Comment by DaMatrix** [comment]
I'll just do that right here then

**Comment by DaMatrix** [comment]
There we go :D sequinland.yml

**Comment by DaMatrix** [comment]
This is mergable and functional now

**Comment by ghost** [comment]
@MrPowerGamerBR Accept? :)

**Pull request closed without merging**
